title:Boma Kingsley Wilcox
logo:BOMA.png
description: Passionate about turning data into insights, Specialize in collecting, cleaning, and analyzing data to drive informed decision-making.
#show_downloads: true
#google_analystics:
theme:jekyll-theme-minimal
